import type { Metadata } from 'next';
import './globals.css';
import 'aos/dist/aos.css';
import AOSProvider from './providers/AOSProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <AOSProvider />
                {children}
            </body>
        </html>
    );
}
