import type { Metadata } from 'next';
import { Inter, Cairo } from 'next/font/google';
import { Locale, i18n } from '@/i18n.config';
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] });
const cairo = Cairo({ subsets: ['arabic'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export async function generateStaticParams() {
    return i18n.locales.map(locale => ({ lang: locale }));
}

export default function RootLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: { lang: Locale };
}) {
    return (
        <main
            suppressHydrationWarning
            className={classNames(inter.className, cairo.className)}
            dir={params.lang === 'ar' ? 'rtl' : 'ltr'}
        >
            {children}
        </main>
    );
}
